
server:
  port: 8080

logging:
  level:
    root:  debug

webclient:
  timeout: # Time Unit as second
    connection: 10
    read: 10
    write: 10

mapping:
  primary:
    "[/.*]": http://127.0.0.1:8080


